### ISSUE TITLE
Creating 'Regulatory/Legislative Filings' bucket

### ISSUE THREAD

**Issue by sloane101** [newamericafoundation/newamerica-cms#916] opened 2016-05-26 18:01 UTC
We had briefly talked about this before launch, but I wanted to reflag it. We need a bucket for regulatory and legislative filings as a publication type. Can contain the same fields as articles, but needs to be titled Legislative/Regulatory filings.

**Comment by kjacks** [comment] 2016-09-23 19:48
Duplicate of #540

**Closed by kjacks** 2016-09-23 19:48 UTC
