### ISSUE TITLE
Author order flipping

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1104] opened 2016-08-04 14:29 UTC
Before:
<img width="503" alt="screen shot 2016-08-04 at 10 27 21 am" src="https://cloud.githubusercontent.com/assets/17412375/17405609/301b3438-5a2e-11e6-83cf-2f7b4a0bd1e3.png">

After:
<img width="257" alt="screen shot 2016-08-04 at 10 27 26 am" src="https://cloud.githubusercontent.com/assets/17412375/17405616/33ee1d8c-5a2e-11e6-80e4-56bfc6bfeb88.png">

**Comment by kjacks** [comment] 2016-08-04 15:56
Duplicate of #942

**Closed by kjacks** 2016-08-04 15:56 UTC
Labels: August 2016
