### ISSUE TITLE
"Former fellows" button doesn't go anywhere

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1397] opened 2019-08-19 17:01 UTC
The button at the bottom of this page is supposed to load the former fellows.
https://www.newamerica.org/fellows/our-people/

The page they're using instead is
https://www.newamerica.org/fellows/about/alumni-roster/

This could be solved either by a) making it work correctly, with clicking the button loading all of the former fellows or by b) making that button link to the alumni roster page. @mariaelkin, thoughts? I lean toward the latter, since they have content on the alumni roster page.

**Comment by kevinhowbrook** [comment] 2019-09-03 11:42
Hey @nmorduch 

Having looked into this, it looks like the button is working but the request the button calls is responding with no data:
`https://www.newamerica.org/api/fellow/?program_id=132&page_size=25&former=true`

Fixing the button is probably the best option here, or more specifically pinning down why it's no longer working. I suspect it's because some people that are `former=True` are not linked to any programs, e.g https://www.newamerica.org/admin/pages/12398/edit/

To tackle this it's best to relate some `persons` pages to a program and set them as `former=True` on staging.

Option b isn't a bad solution, but if there is functionality like this built-in it would be better to fix and use it, however if over the life cycle of the site that the way former fellows are handled (ie being unrelated to programs once set to former) then it's wise to replace the button with your suggestion.

**Comment by nmorduch** [comment] 2019-09-03 15:06
Let's just make the button link to the page they're using, at least for now. Especially since I should eventually be changing how this page works.

**Comment by mariaelkin** [comment] 2019-09-03 15:24
Yes, let's just change the button to go the link that they're using, for the time being. The Fellows Program is the only one that actively uses the Former Fellows button. Fixing former fellows' bios so they have a designated program in addition to being marked former is something we can do, but will take some time. @kevinhowbrook is it easy for you to pull a list of people who are causing the problem? If not, nbd, we can just cross-reference from the alumni roster page. This is a medium-low priority.

**Comment by nmorduch** [comment] 2019-09-03 15:36
@mariaelkin do I understand correctly that making the button go to the alumni roster is high priority, and having it be functional as intended is what is medium-low priority?

**Comment by mariaelkin** [comment] 2019-09-03 15:44
What's the time estimate on just making the button go to the alumni roster? Depending on time, I think we make that fix and call it a day, but it's the least high priority of the high priority things.

Thinking about it more, I don't think it's worth our time to make it work as intended. Even working as intended, it wasn't doing what the program needed.

**Comment by nmorduch** [comment] 2019-09-09 13:59
Making it a hard-coded link to the alumni roster should, I think, be trivial. And then when I eventually redo people pages we'd think about what the best option would be.

**Comment by nmorduch** [comment] 2020-01-09 17:25
Hm this is used successfully by [New America CA](https://www.newamerica.org/ca/our-people/), so I don't want to get rid of it.

Testing locally, yes the answer is that they need to be associated to programs. If one associates each person to a program (e.g. the Fellows program) it fixes it. But yes, perhaps the Fellows program would do best with just the hard coding, at least for now.

**Comment by nmorduch** [comment] 2020-01-09 17:32
I will also note that this isn't a great setup for how to do former fellows in general, thinking about how sometimes people are no longer associated with a given program and are currently associated with another. perhaps the correct option would be to have an option to add former affiliations, rather than being able to associate someone to a program + mark them as generally former.

**Comment by jckpn** [comment] 2020-01-16 14:12
Are you okay for this to be closed @nmorduch as it was fixed in #1474?

**Closed** 2020-01-16 15:05 UTC
Labels: 3 low, area/react, bug
