### ISSUE TITLE
Tidy up Printing

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#436] opened 2016-04-18 22:06 UTC
Doesn't look terrible right now but could be better...

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-18 at 6.05.08 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=114025953385124)
#url https://app.asana.com/0/0/114025953385120/f
---[aa]

**Comment by kjacks** [comment] 2016-06-06 19:50
Duplicate of #968

**Closed by kjacks** 2016-06-06 19:50 UTC
Labels: June 2016
