### ISSUE TITLE
In-Depth: Collapse and Expand

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1095] opened 2016-07-25 18:04 UTC
![screen shot 2016-07-25 at 2 03 03 pm](https://cloud.githubusercontent.com/assets/13524901/17111696/bfa1e8e2-5270-11e6-8e63-862fa1f4022d.png)

**Comment by kjacks** [comment] 2016-07-25 18:17
duplicate of #1093

**Closed by kjacks** 2016-07-25 18:17 UTC
