### ISSUE TITLE
Email Contact Button

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#515] opened 2016-04-21 18:00 UTC
Is it possible to have her email contact information listed in text at the end of the bio instead of the button? Maybe it's a Joanne problem, but I can't stand the email link thing because it launches the mail app instead of allowing me to easily copy and paste her email address.

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 1.21.54 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583024)
#url https://app.asana.com/0/0/115014319583021/f
---[aa]

**Comment by rossvanderlinde** [comment] 2016-04-21 18:15
We were struggling with this, because we also hate the launch-outlook thing. Moving to the summer, as it's a secondary priority, but worth returning to

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment] 2016-05-18 16:20
Would be good to discuss this and other bio features/layout at next web stakeeholder

**Comment by kjacks** [comment] 2016-09-23 19:36
Duplicate of #300

**Closed by kjacks** 2016-09-23 19:36 UTC
Labels: July 2016, Next Web Stakeholder
