### ISSUE TITLE
Example: Mobile/Chrome: Arrow Cuts Off

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#652] opened 2016-04-29 19:15 UTC
Problem: the arrow next to the New America icon cuts off at screen sizes less than 300px wide.
Browser: Chrome version 1.2.3.4.
Screen Size: Mobile (Android), only below 300px width.
Possible Solution: Move arrow to front using z-Index

[--- This issue is linked with an Asana task
#attachments [unnamed.png](https://app.asana.com/app/asana/-/download_asset?asset_id=116116869353019)
#url https://app.asana.com/0/0/116116869353016/f
---[aa]

**Comment by kjacks** [comment] 2016-05-03 19:58
Duplicate of #613

**Closed by kjacks** 2016-05-03 19:58 UTC
