### ISSUE TITLE
Some hyperlinked text not turning green on hover

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1105] opened 2016-08-04 14:33 UTC
e.g. "Far and Away" and "#FarandAway" here: http://www.newamerica.org/nyc/events/far-and-away/

**Comment by rossvanderlinde** [comment] 2016-09-29 15:26
When you add bold/italics to an a tag it'll stop taking on that mouseover effect; should be pretty easy to fix.

**Comment by LomaxRx** [comment] 2016-10-17 13:48
duplicate of #1109?

**Closed** 2016-11-30 16:28 UTC
Labels: Bug, Low Priority
