### ISSUE TITLE
[2-3hrs] Some items duplicated on some program homepages

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1453] opened 2019-12-05 17:43 UTC
See https://www.newamerica.org/education-policy/

It seems that only the first few are duplicated, and I really have no idea why. They're not doubled in the backend as far as I can tell.

**Comment by nmorduch** [comment] 2019-12-06 21:47
We've now had 3 independent complaints about this, which suggests to me that it's recent, which suggests to me that it's related to the recent changes

**Comment by kaedroho** [comment] 2019-12-09 11:21
This is likely (but not 100% sure) to have been caused by the React changes I made to allow the new pagination method to be used on the publications view. I think it would take around 2 - 3 hours to investigate and resolve.

**Comment by nmorduch** [comment] 2019-12-11 16:25
We also got this follow-up:
> some people are reporting that they’re having a similar problem with the displays on the publications page when they choose “show more”. As in the first few blogs that display are repeating. (And all the X’s have turned into slashes when you open/close the drop downs).

**Comment by kaedroho** [comment] 2019-12-13 14:56
Spent some time looking at this today, I think the issue exists somewhere within the `InfiniteLoadMore` component. I haven't pinned down the issue with it yet though.

The API isn't returning duplicates, and it looks like the reducer is combining them correctly too.

I've opened up a WIP pull request that will later contain the fix for this (currently contains a little bit of refactoring of `InfiniteLoadMore`). https://github.com/newamericafoundation/newamerica-cms/pull/1454

**Comment by nmorduch** [comment] 2019-12-20 15:29
This is looking good to me on staging!

**Closed** 2019-12-20 18:02 UTC
Labels: 1 high, bug, tbx
